export const categories = [
  { value: "tien-hiep", label: "Tiên Hiệp" },
  { value: "ngon-tinh", label: "Ngôn Tình" },
  { value: "hien-dai", label: "Hiện Đại" },
  { value: "goc-nhin-nu", label: "Góc Nhìn Nữ" },
  { value: "co-dai", label: "Cổ Đại" },
  { value: "ngu-thu", label: "Ngự Thú" },
  { value: "vong-du", label: "Võng Du" },
  { value: "mat-the", label: "Mạt Thế" },
  { value: "phan-phai", label: "Phản Phái" },
  { value: "khoa-huyen", label: "Khoa Huyễn" },
  { value: "hong-hoang", label: "Hồng Hoang" },
  { value: "chien-tranh", label: "Chiến Tranh" },
  { value: "vo-si", label: "Vô Sỉ" },
  { value: "he-thong", label: "Hệ Thống" },
  { value: "huyen-huyen", label: "Huyền Huyễn" },
  { value: "dien-van", label: "Điền Văn" },
  { value: "sang-van", label: "Sảng Văn" },
  { value: "do-thi", label: "Đô Thị" },
  { value: "di-nang", label: "Dị Năng" },
  { value: "co-tri", label: "Cơ Trí" },
  { value: "dong-phuong", label: "Đông Phương" },
  { value: "xuyen-khong", label: "Xuyên Không" },
  { value: "linh-di", label: "Linh Dị" },
  { value: "trong-sinh", label: "Trọng Sinh" },
  { value: "di-gioi", label: "Dị Giới" },
  { value: "trinh-tham", label: "Trinh Thám" },
  { value: "vo-hiep", label: "Võ Hiệp" },
  { value: "hoan-thanh", label: "Hoàn Thành" },
  { value: "premium", label: "Premium" },
  { value: "mien-phi", label: "Miễn Phí" },
  { value: "he", label: "HE" },
  { value: "nu-cuong", label: "Nữ Cường" },
  { value: "hai-huoc", label: "Hài Hước" },
  { value: "xay-dung-the-luc", label: "Xây Dựng Thế Lực" },
  { value: "goc-nhin-nam", label: "Góc Nhìn Nam" },
  { value: "cao-vo-the-gioi", label: "Cao Võ Thế Giới" },
  { value: "dong-nhan", label: "Đồng Nhân" },
  { value: "huyen-nghi", label: "Huyền Nghi" },
  { value: "thiet-huyen", label: "Thiết Huyền" },
  { value: "quy-bi", label: "Quỷ Bí" },
  { value: "nhiet-huyet", label: "Nhiệt Huyết" },
  { value: "vo-dich", label: "Vô Địch" },
  { value: "linh-di", label: "Linh Dị" },
  { value: "linh-di", label: "Linh Dị" },
  { value: "linh-di", label: "Linh Dị" },
  { label: "Lãnh Khóc", value: "lanh-khoc" },
  { label: "Nhẹ nhàng", value: "nhe-nhang" },
  { label: "Phàm Nhân", value: "pham-nhan" },
  { label: "Điềm Đạm", value: "diem-dam" },
  { label: "Dã Sử", value: "da-su" },
  { label: "Ngôn Tình", value: "ngon-tinh" },
];
