export const categories = [
  { slug: "tien-hiep", title: "Tiên Hiệp" },
  { slug: "ngon-tinh", title: "Ngôn Tình" },
  { slug: "vong-du", title: "Võng Du" },
  { slug: "mat-the", title: "Mạt Thế" },
  { slug: "phan-phai", title: "Phản Phái" },
  { slug: "khoa-huyen", title: "Khoa Huyễn" },
  { slug: "hong-hoang", title: "Hồng Hoang" },
  { slug: "chien-tranh", title: "Chiến Tranh" },
  { slug: "vo-si", title: "Vô Sỉ" },
  { slug: "he-thong", title: "Hệ Thống" },
  { slug: "huyen-huyen", title: "Huyền Huyễn" },
  { slug: "dien-van", title: "Điền Văn" },
  { slug: "sang-van", title: "Sảng Văn" },
  { slug: "do-thi", title: "Đô Thị" },
  { slug: "di-nang", title: "Dị Năng" },
  { slug: "co-tri", title: "Cơ Trí" },
  { slug: "dong-phuong", title: "Đông Phương" },
  { slug: "xuyen-khong", title: "Xuyên Không" },
  { slug: "linh-di", title: "Linh Dị" },
  { slug: "trong-sinh", title: "Trọng Sinh" },
  { slug: "di-gioi", title: "Dị Giới" },
  { slug: "trinh-tham", title: "Trinh Thám" },
  { slug: "vo-hiep", title: "Võ Hiệp" },
  { slug: "hoan-thanh", title: "Hoàn Thành" },
  { slug: "premium", title: "Premium" },
  { slug: "mien-phi", title: "Miễn Phí" },
];
